name: Pipeline de Testes Continuos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testar-aplicacao:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v6

    - name: Configurar o Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 25

    - name: Instalar Dependencias
      run: npm ci

    - name: Executar os Testes Automatizados
      run: npm test -- --coverage

    - name: Upload de cov report
      id: upload-cov
      uses: actions/upload-artifact@v7
      with:
        name: cov-report
        path: coverage/
        
    - name: Comentário de onde está o artefato
      uses: peter-evans/create-or-update-comment@v5
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Relatório de coverage: ${{ steps.upload-cov.outputs.artifact-url }}
