name: Pipeline de Testes Continuos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testar-aplicacao:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar codigo do repositorio
      uses: actions/checkout@v6

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 25

    - name: Instalar Dependencias
      run: npm ci

    - name: Executar os Testes Automatizados
      run: npm test -- --coverage
